const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let manifests={pages:[],articles:[],library:[]}, config={menu:[]}, excluded=[];
async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`HTTP ${r.status}`);return j}
function tab(name){document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id==='tab-'+name));document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>tab(b.dataset.go));
function renderPages(q=''){q=q.toLowerCase();const a=manifests.pages.filter(x=>(x.title+' '+x.path).toLowerCase().includes(q));$('staticPages').innerHTML=a.map(x=>`<div class="item"><div class="item-main"><div class="item-title">${esc(x.title)}</div><div class="item-meta">/${esc(x.path)}${x.override?' · modificata':''}${x.deleted?' · eliminata':''}</div></div><button class="btn btn-light" data-page="${esc(x.path)}">Modifica</button></div>`).join('')||'<div class="muted">Nessun risultato.</div>';document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>openContent(b.dataset.page,'page'));}
function renderArticles(q=''){q=q.toLowerCase();const a=manifests.articles.filter(x=>(x.title+' '+x.path+' '+(x.pmid||'')).toLowerCase().includes(q));$('articlesList').innerHTML=a.map(x=>`<div class="item"><div class="item-main"><div class="item-title">${esc(x.title)}</div><div class="item-meta">${esc(x.pmid?'PMID '+x.pmid+' · ':'')}/${esc(x.path)}${x.override?' · modificato':''}${x.deleted?' · eliminato':''}</div></div><button class="btn btn-light" data-article="${esc(x.path)}">Modifica</button></div>`).join('')||'<div class="muted">Nessun risultato.</div>';document.querySelectorAll('[data-article]').forEach(b=>b.onclick=()=>openContent(b.dataset.article,'article'));}
async function openContent(path,type){try{const j=await api('/api/site-admin/content?path='+encodeURIComponent(path));$(type==='page'?'pagePath':'articlePath').value=path;$(type==='page'?'pagePathView':'articlePathView').value='/'+path;$(type==='page'?'pageHtml':'articleHtml').value=j.html||'';$(type==='page'?'pageStatus':'articleStatus').textContent=j.deleted?'Attualmente eliminato/nascosto.':'';}catch(e){$(type==='page'?'pageStatus':'articleStatus').textContent=e.message}}
async function saveContent(type){const path=$(type==='page'?'pagePath':'articlePath').value, html=$(type==='page'?'pageHtml':'articleHtml').value;if(!path)return;try{await api('/api/site-admin/content',{method:'PUT',body:JSON.stringify({path,html})});$(type==='page'?'pageStatus':'articleStatus').textContent='Modifica salvata.';await loadManifests();}catch(e){$(type==='page'?'pageStatus':'articleStatus').textContent=e.message}}
async function contentAction(type,action){const path=$(type==='page'?'pagePath':'articlePath').value;if(!path)return;if(action==='delete'&&!confirm(type==='article'?'Eliminare questo articolo dal sito?':'Nascondere questa pagina dal sito?'))return;try{await api('/api/site-admin/content',{method:action==='restore'?'DELETE':'POST',body:JSON.stringify({path,action})});$(type==='page'?'pageStatus':'articleStatus').textContent=action==='restore'?'Versione originale ripristinata.':'Contenuto eliminato/nascosto.';await loadManifests();await openContent(path,type);}catch(e){$(type==='page'?'pageStatus':'articleStatus').textContent=e.message}}
$('saveStaticPage').onclick=()=>saveContent('page');$('restoreStaticPage').onclick=()=>contentAction('page','restore');$('deleteStaticPage').onclick=()=>contentAction('page','delete');$('saveArticle').onclick=()=>saveContent('article');$('restoreArticle').onclick=()=>contentAction('article','restore');$('deleteArticle').onclick=()=>contentAction('article','delete');$('pageSearch').oninput=e=>renderPages(e.target.value);$('articleSearch').oninput=e=>renderArticles(e.target.value);
function renderMenu(){$('menuRows').innerHTML=(config.menu||[]).map((x,i)=>`<div class="menu-row" data-i="${i}"><input class="men wide" data-k="label_en" value="${esc(x.label_en)}"><input class="men wide" data-k="label_it" value="${esc(x.label_it)}"><input class="men wide" data-k="href" value="${esc(x.href)}"><select class="men" data-k="group"><option value="main" ${x.group!=='more'?'selected':''}>Principale</option><option value="more" ${x.group==='more'?'selected':''}>Altro</option></select><select class="men" data-k="visible"><option value="true" ${x.visible!==false?'selected':''}>Visibile</option><option value="false" ${x.visible===false?'selected':''}>Nascosta</option></select><input class="men" data-k="order" type="number" value="${Number(x.order)||0}"><button class="btn btn-danger" data-rm="${i}">×</button></div>`).join('');document.querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>{config.menu.splice(+b.dataset.rm,1);renderMenu()})}
function readMenu(){document.querySelectorAll('.menu-row').forEach(r=>r.querySelectorAll('.men').forEach(el=>{let v=el.value;if(el.dataset.k==='visible')v=v==='true';if(el.dataset.k==='order')v=Number(v);config.menu[+r.dataset.i][el.dataset.k]=v}))}
$('addMenu').onclick=()=>{readMenu();config.menu.push({label_en:'New',label_it:'Nuova',href:'#',visible:true,group:'main',order:(config.menu.length+1)*10});renderMenu()};$('saveMenu').onclick=async()=>{try{readMenu();config=(await api('/api/site-admin/config',{method:'PUT',body:JSON.stringify(config)})).config;renderMenu();$('menuStatus').textContent='Menu salvato.'}catch(e){$('menuStatus').textContent=e.message}};
function renderLibrary(q=''){q=q.toLowerCase();const a=manifests.library.filter(x=>!excluded.includes(x.pmid)&&(x.title+' '+x.pmid+' '+(x.doi||'')).toLowerCase().includes(q)).slice(0,150);$('libraryList').innerHTML=a.map(x=>`<div class="item"><div class="item-main"><div class="item-title">${esc(x.title)}</div><div class="item-meta">PMID ${esc(x.pmid)}${x.doi?' · DOI '+esc(x.doi):''}</div></div><button class="btn btn-danger" data-exclude="${esc(x.pmid)}">Escludi</button></div>`).join('')||'<div class="muted">Nessun risultato.</div>';const ex=manifests.library.filter(x=>excluded.includes(x.pmid));$('excludedList').innerHTML=ex.map(x=>`<div class="item"><div class="item-main"><div class="item-title">${esc(x.title)}</div><div class="item-meta">PMID ${esc(x.pmid)}</div></div><button class="btn btn-light" data-restore-pmid="${esc(x.pmid)}">Ripristina</button></div>`).join('')||'<div class="muted">Nessuno studio escluso.</div>';document.querySelectorAll('[data-exclude]').forEach(b=>b.onclick=()=>setExcluded(b.dataset.exclude,true));document.querySelectorAll('[data-restore-pmid]').forEach(b=>b.onclick=()=>setExcluded(b.dataset.restorePmid,false));}
async function setExcluded(pmid,on){try{const j=await api('/api/site-admin/library-exclusions',{method:on?'POST':'DELETE',body:JSON.stringify({pmid})});excluded=j.excluded||[];renderLibrary($('librarySearch').value);$('libraryStatus').textContent=on?'Studio escluso in modo persistente.':'Studio ripristinato.';}catch(e){$('libraryStatus').textContent=e.message}}$('librarySearch').oninput=e=>renderLibrary(e.target.value);
async function loadManifests(){const j=await api('/api/site-admin/manifests');manifests=j;renderPages($('pageSearch').value);renderArticles($('articleSearch').value);renderLibrary($('librarySearch').value)}
(async()=>{try{config=await api('/api/site-admin/config');const ex=await api('/api/site-admin/library-exclusions');excluded=ex.excluded||[];renderMenu();await loadManifests()}catch(e){$('menuStatus').textContent=e.message}})();
let customPages=[];
function renderCustomPages(){ $('customPages').innerHTML=customPages.map(p=>`<div class="item"><div class="item-main"><div class="item-title">${esc(p.title)}</div><div class="item-meta">/p/${esc(p.slug)} · ${esc(p.status)}</div></div><button class="btn btn-light" data-custom="${esc(p.slug)}">Modifica</button></div>`).join('')||'<div class="muted">Nessuna pagina creata dal backend.</div>';document.querySelectorAll('[data-custom]').forEach(b=>b.onclick=()=>editCustom(b.dataset.custom));}
async function loadCustom(){try{customPages=(await api('/api/site-admin/pages')).pages||[];renderCustomPages()}catch(e){}}
function editCustom(slug){const p=customPages.find(x=>x.slug===slug);if(!p)return;$('customEditor').hidden=false;$('customEditSlug').value=p.slug;$('customTitle').value=p.title||'';$('customSlug').value=p.slug;$('customSlug').disabled=true;$('customDescription').value=p.description||'';$('customStatus').value=p.status||'draft';$('customBody').value=p.body_html||'';}
$('newCustomPage').onclick=()=>{$('customEditor').hidden=false;$('customEditSlug').value='';$('customTitle').value='';$('customSlug').value='';$('customSlug').disabled=false;$('customDescription').value='';$('customStatus').value='draft';$('customBody').value='';};
$('saveCustomPage').onclick=async()=>{try{const slug=$('customEditSlug').value,b={title:$('customTitle').value,slug:$('customSlug').value,description:$('customDescription').value,status:$('customStatus').value,body_html:$('customBody').value};await api(slug?'/api/site-admin/pages/'+slug:'/api/site-admin/pages',{method:slug?'PUT':'POST',body:JSON.stringify(b)});$('customStatusMsg').textContent='Pagina salvata.';await loadCustom();}catch(e){$('customStatusMsg').textContent=e.message}};
$('deleteCustomPage').onclick=async()=>{const slug=$('customEditSlug').value;if(!slug||!confirm('Eliminare questa pagina?'))return;try{await api('/api/site-admin/pages/'+slug,{method:'DELETE'});$('customEditor').hidden=true;await loadCustom();}catch(e){$('customStatusMsg').textContent=e.message}};
loadCustom();
