const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let manifests={pages:[],articles:[],library:[],defaultMenu:[]}, config={menu:[]}, excluded=[], customPages=[], sourceDocs={page:null,article:null};
async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`HTTP ${r.status}`);return j}
function tab(name){document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id==='tab-'+name));document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>tab(b.dataset.go));
function makeToolbar(el){const id=el.dataset.editor;el.innerHTML=`<select data-cmd="formatBlock"><option value="p">Paragrafo</option><option value="h2">Titolo 2</option><option value="h3">Titolo 3</option><option value="blockquote">Citazione</option></select><button data-cmd="bold"><b>B</b></button><button data-cmd="italic"><i>I</i></button><button data-cmd="underline"><u>U</u></button><button data-cmd="insertUnorderedList">• Elenco</button><button data-cmd="insertOrderedList">1. Elenco</button><button data-act="link">Link</button><button data-act="unlink">Togli link</button><button data-act="undo">↶</button><button data-act="redo">↷</button>`;el.onmousedown=e=>{const b=e.target.closest('button');if(b)e.preventDefault()};el.onchange=e=>{if(e.target.dataset.cmd){document.getElementById(id).focus();document.execCommand(e.target.dataset.cmd,false,e.target.value)}};el.onclick=e=>{const b=e.target.closest('button');if(!b)return;document.getElementById(id).focus();if(b.dataset.cmd)document.execCommand(b.dataset.cmd,false,null);if(b.dataset.act==='link'){const u=prompt('Indirizzo del link (https://…):');if(u)document.execCommand('createLink',false,u)}if(b.dataset.act==='unlink')document.execCommand('unlink');if(b.dataset.act==='undo')document.execCommand('undo');if(b.dataset.act==='redo')document.execCommand('redo')};}
document.querySelectorAll('.visual-toolbar').forEach(makeToolbar);
function extractEditable(html){const d=new DOMParser().parseFromString(html,'text/html');const node=d.querySelector('main')||d.body;return {doc:d,node,inner:node.innerHTML};}
function rebuild(type){const ed=$(type==='page'?'pageVisual':'articleVisual'),state=sourceDocs[type];if(!state)return '';state.node.innerHTML=ed.innerHTML;return '<!doctype html>\n'+state.doc.documentElement.outerHTML;}
function renderPages(q=''){q=q.toLowerCase();const a=manifests.pages.filter(x=>(x.title+' '+x.path).toLowerCase().includes(q));$('staticPages').innerHTML=a.map(x=>`<div class="item ${x.deleted?'deleted':''}"><div class="item-main"><div class="item-title">${esc(x.title)}${x.override?'<span class="badge">modificata</span>':''}${x.deleted?'<span class="badge">nascosta</span>':''}</div><div class="item-meta">/${esc(x.path)}</div></div><button class="btn btn-light" data-page="${esc(x.path)}">Modifica</button></div>`).join('')||'<div class="muted">Nessun risultato.</div>';document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>openContent(b.dataset.page,'page'));}
function renderArticles(q=''){q=q.toLowerCase();const a=manifests.articles.filter(x=>(x.title+' '+x.path+' '+(x.pmid||'')).toLowerCase().includes(q));$('articlesList').innerHTML=a.map(x=>`<div class="item ${x.deleted?'deleted':''}"><div class="item-main"><div class="item-title">${esc(x.title)}${x.override?'<span class="badge">modificato</span>':''}${x.deleted?'<span class="badge">eliminato</span>':''}</div><div class="item-meta">${esc(x.pmid?'PMID '+x.pmid+' · ':'')}/${esc(x.path)}</div></div><div class="toolbar"><button class="btn btn-light" data-article="${esc(x.path)}">Modifica</button>${x.deleted?`<button class="btn btn-light" data-article-restore="${esc(x.path)}">Ripristina</button>`:`<button class="btn btn-danger" data-article-delete="${esc(x.path)}">Elimina</button>`}</div></div>`).join('')||'<div class="muted">Nessun risultato.</div>';document.querySelectorAll('[data-article]').forEach(b=>b.onclick=()=>openContent(b.dataset.article,'article'));document.querySelectorAll('[data-article-delete]').forEach(b=>b.onclick=()=>articleListAction(b.dataset.articleDelete,'delete'));document.querySelectorAll('[data-article-restore]').forEach(b=>b.onclick=()=>articleListAction(b.dataset.articleRestore,'restore'));}
async function articleListAction(path,action){const msg=action==='delete'?'Eliminare questo articolo dal sito? Rimarrà escluso finché non lo ripristini.':'Ripristinare questo articolo sul sito?';if(!confirm(msg))return;try{await api('/api/site-admin/content',{method:action==='restore'?'DELETE':'POST',body:JSON.stringify({path,action})});await loadManifests();}catch(e){alert(e.message)}}
async function openContent(path,type){const status=$(type==='page'?'pageStatus':'articleStatus');try{let j=await api('/api/site-admin/content?path='+encodeURIComponent(path));if(j.deleted){status.textContent='Questo contenuto è attualmente nascosto. Ripristinalo per modificarlo.';j=await api('/api/site-admin/content?path='+encodeURIComponent(path)+'&original=1')}const parsed=extractEditable(j.html||'');sourceDocs[type]=parsed;$(type==='page'?'pageVisual':'articleVisual').innerHTML=parsed.inner;$(type==='page'?'pageHtml':'articleHtml').value=j.html||'';$(type==='page'?'pagePath':'articlePath').value=path;$(type==='page'?'pagePathView':'articlePathView').textContent='/'+path;const preview=$(type==='page'?'pagePreview':'articlePreview');preview.href='https://ketogenicresearch.org/'+path;$(type==='page'?'pageEditor':'articleEditor').hidden=false;status.textContent=j.override?'Stai modificando la versione personalizzata.':'Versione originale caricata.';}catch(e){status.textContent=e.message}}
async function saveContent(type){const path=$(type==='page'?'pagePath':'articlePath').value;if(!path)return;const html=rebuild(type);try{await api('/api/site-admin/content',{method:'PUT',body:JSON.stringify({path,html})});$(type==='page'?'pageStatus':'articleStatus').textContent='Modifiche salvate e pubblicate.';await loadManifests();}catch(e){$(type==='page'?'pageStatus':'articleStatus').textContent=e.message}}
async function contentAction(type,action){const path=$(type==='page'?'pagePath':'articlePath').value;if(!path)return;const msg=action==='delete'?(type==='article'?'Nascondere questo articolo dal sito? Potrai ripristinarlo.':'Nascondere questa pagina dal sito? Potrai ripristinarla.'):'Ripristinare la versione originale? Le modifiche manuali verranno rimosse.';if(!confirm(msg))return;try{await api('/api/site-admin/content',{method:action==='restore'?'DELETE':'POST',body:JSON.stringify({path,action})});$(type==='page'?'pageStatus':'articleStatus').textContent=action==='restore'?'Versione originale ripristinata.':'Contenuto nascosto.';await loadManifests();await openContent(path,type);}catch(e){$(type==='page'?'pageStatus':'articleStatus').textContent=e.message}}
$('saveStaticPage').onclick=()=>saveContent('page');$('restoreStaticPage').onclick=()=>contentAction('page','restore');$('deleteStaticPage').onclick=()=>contentAction('page','delete');$('saveArticle').onclick=()=>saveContent('article');$('restoreArticle').onclick=()=>contentAction('article','restore');$('deleteArticle').onclick=()=>contentAction('article','delete');$('pageSearch').oninput=e=>renderPages(e.target.value);$('articleSearch').oninput=e=>renderArticles(e.target.value);
$('applyPageHtml').onclick=()=>{const p=extractEditable($('pageHtml').value);sourceDocs.page=p;$('pageVisual').innerHTML=p.inner};$('applyArticleHtml').onclick=()=>{const p=extractEditable($('articleHtml').value);sourceDocs.article=p;$('articleVisual').innerHTML=p.inner};
function pageChoices(selected=''){const rows=[...manifests.pages.filter(x=>!x.deleted).map(x=>({label:x.title,href:'/'+x.path})),...customPages.filter(x=>x.status==='published').map(x=>({label:x.title,href:'https://library.ketogenicresearch.org/p/'+x.slug}))];let out='<option value="">— scegli una pagina —</option>'+rows.map(x=>`<option value="${esc(x.href)}" ${x.href===selected?'selected':''}>${esc(x.label)}</option>`).join('');out+=`<option value="__custom__" ${selected&& !rows.some(x=>x.href===selected)?'selected':''}>Link personalizzato…</option>`;return out;}
function renderMenu(){const rows=config.menu||[];$('menuRows').innerHTML=rows.map((x,i)=>{const custom=x.href && ![...manifests.pages.map(p=>'/'+p.path),...customPages.map(p=>'https://library.ketogenicresearch.org/p/'+p.slug)].includes(x.href);return `<div class="menu-row" data-i="${i}"><div class="menu-labels"><input class="men" data-k="label_en" aria-label="Nome inglese" value="${esc(x.label_en||'')}"><input class="men" data-k="label_it" aria-label="Nome italiano" value="${esc(x.label_it||'')}"></div><div class="menu-link"><select class="men link-select" data-k="hrefSelect">${pageChoices(x.href)}</select><input class="men custom-link" data-k="hrefCustom" value="${esc(custom?x.href:'')}" placeholder="https://…" ${custom?'':'hidden'}></div><select class="men" data-k="group"><option value="main" ${x.group!=='more'?'selected':''}>Principale</option><option value="more" ${x.group==='more'?'selected':''}>Altro</option></select><select class="men" data-k="visible"><option value="true" ${x.visible!==false?'selected':''}>Visibile</option><option value="false" ${x.visible===false?'selected':''}>Nascosta</option></select><input class="men" data-k="order" type="number" value="${Number(x.order)||0}"><button class="btn btn-danger" data-rm="${i}" title="Elimina solo dal menu">Elimina</button></div>`}).join('')||'<div class="muted">Nessuna voce nel menu.</div>';document.querySelectorAll('.link-select').forEach(s=>s.onchange=()=>{const inp=s.parentElement.querySelector('.custom-link');inp.hidden=s.value!=='__custom__';if(!inp.hidden)inp.focus()});document.querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>{if(confirm('Rimuovere questa voce dal menu? La pagina collegata non verrà eliminata.')){config.menu.splice(+b.dataset.rm,1);renderMenu()}})}
function readMenu(){document.querySelectorAll('.menu-row').forEach(r=>{const x=config.menu[+r.dataset.i];r.querySelectorAll('.men').forEach(el=>{const k=el.dataset.k;if(k==='label_en'||k==='label_it'||k==='group')x[k]=el.value;if(k==='visible')x.visible=el.value==='true';if(k==='order')x.order=Number(el.value)});const sel=r.querySelector('[data-k="hrefSelect"]'),custom=r.querySelector('[data-k="hrefCustom"]');x.href=sel.value==='__custom__'?custom.value.trim():sel.value;});}
$('addMenu').onclick=()=>{readMenu();config.menu.push({label_en:'',label_it:'',href:'',visible:true,group:'main',order:(config.menu.length+1)*10});renderMenu()};$('saveMenu').onclick=async()=>{try{readMenu();if(config.menu.some(x=>!x.label_en&&!x.label_it))throw new Error('Inserisci il nome per ogni voce.');if(config.menu.some(x=>!x.href))throw new Error('Collega ogni voce a una pagina o a un link.');config=(await api('/api/site-admin/config',{method:'PUT',body:JSON.stringify(config)})).config;renderMenu();$('menuStatus').textContent='Menu salvato e pubblicato.'}catch(e){$('menuStatus').textContent=e.message}};$('resetMenu').onclick=()=>{if(confirm('Ripristinare il menu originale del sito?')){config.menu=structuredClone(manifests.defaultMenu||[]);renderMenu();$('menuStatus').textContent='Menu originale caricato. Premi “Salva menu” per pubblicarlo.'}};
function renderLibrary(q=''){q=q.toLowerCase();const a=manifests.library.filter(x=>!excluded.includes(x.pmid)&&(x.title+' '+x.pmid+' '+(x.doi||'')).toLowerCase().includes(q)).slice(0,150);$('libraryList').innerHTML=a.map(x=>`<div class="item"><div class="item-main"><div class="item-title">${esc(x.title)}</div><div class="item-meta">PMID ${esc(x.pmid)}${x.doi?' · DOI '+esc(x.doi):''}</div></div><button class="btn btn-danger" data-exclude="${esc(x.pmid)}">Escludi</button></div>`).join('')||'<div class="muted">Nessun risultato.</div>';const ex=manifests.library.filter(x=>excluded.includes(x.pmid));$('excludedList').innerHTML=ex.map(x=>`<div class="item"><div class="item-main"><div class="item-title">${esc(x.title)}</div><div class="item-meta">PMID ${esc(x.pmid)}</div></div><button class="btn btn-light" data-restore-pmid="${esc(x.pmid)}">Ripristina</button></div>`).join('')||'<div class="muted">Nessuno studio escluso.</div>';document.querySelectorAll('[data-exclude]').forEach(b=>b.onclick=()=>setExcluded(b.dataset.exclude,true));document.querySelectorAll('[data-restore-pmid]').forEach(b=>b.onclick=()=>setExcluded(b.dataset.restorePmid,false));$('statExcluded').textContent=excluded.length;}
async function setExcluded(pmid,on){if(on&&!confirm('Escludere questo studio dalla Library? Rimarrà nella blacklist finché non lo ripristini.'))return;try{const j=await api('/api/site-admin/library-exclusions',{method:on?'POST':'DELETE',body:JSON.stringify({pmid})});excluded=j.excluded||[];renderLibrary($('librarySearch').value);$('libraryStatus').textContent=on?'Studio escluso in modo persistente.':'Studio ripristinato.';}catch(e){$('libraryStatus').textContent=e.message}}$('librarySearch').oninput=e=>renderLibrary(e.target.value);
async function loadManifests(){const j=await api('/api/site-admin/manifests');manifests=j;$('statPages').textContent=j.pages.length+customPages.length;$('statArticles').textContent=j.articles.length;$('statStudies').textContent=j.library.length;renderPages($('pageSearch').value);renderArticles($('articleSearch').value);renderLibrary($('librarySearch').value);renderMenu()}
function renderCustomPages(){$('customPages').innerHTML=customPages.map(p=>`<div class="item"><div class="item-main"><div class="item-title">${esc(p.title)}</div><div class="item-meta">/p/${esc(p.slug)} · ${esc(p.status)}</div></div><button class="btn btn-light" data-custom="${esc(p.slug)}">Modifica</button></div>`).join('')||'<div class="muted">Nessuna pagina creata dal backend.</div>';document.querySelectorAll('[data-custom]').forEach(b=>b.onclick=()=>editCustom(b.dataset.custom));$('statPages').textContent=(manifests.pages?.length||0)+customPages.length;}
async function loadCustom(){try{customPages=(await api('/api/site-admin/pages')).pages||[];renderCustomPages()}catch(e){}}
function editCustom(slug){const p=customPages.find(x=>x.slug===slug);if(!p)return;$('customEditor').hidden=false;$('customEditSlug').value=p.slug;$('customTitle').value=p.title||'';$('customSlug').value=p.slug;$('customSlug').disabled=true;$('customDescription').value=p.description||'';$('customStatus').value=p.status||'draft';$('customVisual').innerHTML=p.body_html||'';}
$('newCustomPage').onclick=()=>{$('customEditor').hidden=false;$('customEditSlug').value='';$('customTitle').value='';$('customSlug').value='';$('customSlug').disabled=false;$('customDescription').value='';$('customStatus').value='draft';$('customVisual').innerHTML='<p>Scrivi qui il contenuto della nuova pagina.</p>';};
$('saveCustomPage').onclick=async()=>{try{const slug=$('customEditSlug').value,b={title:$('customTitle').value,slug:$('customSlug').value,description:$('customDescription').value,status:$('customStatus').value,body_html:$('customVisual').innerHTML};await api(slug?'/api/site-admin/pages/'+slug:'/api/site-admin/pages',{method:slug?'PUT':'POST',body:JSON.stringify(b)});$('customStatusMsg').textContent='Pagina salvata.';await loadCustom();renderMenu()}catch(e){$('customStatusMsg').textContent=e.message}};
$('deleteCustomPage').onclick=async()=>{const slug=$('customEditSlug').value;if(!slug||!confirm('Eliminare definitivamente questa pagina creata dal backend?'))return;try{await api('/api/site-admin/pages/'+slug,{method:'DELETE'});$('customEditor').hidden=true;await loadCustom();renderMenu()}catch(e){$('customStatusMsg').textContent=e.message}};
(async()=>{try{await loadCustom();await loadManifests();config=await api('/api/site-admin/config');if(!Array.isArray(config.menu)||!config.menu.length)config.menu=structuredClone(manifests.defaultMenu||[]);const ex=await api('/api/site-admin/library-exclusions');excluded=ex.excluded||[];renderMenu();renderLibrary('');}catch(e){$('menuStatus').textContent=e.message}})();

// --- Extended safe CMS tools: media, appearance, scientific committee, backup ---
let extendedConfig={director_photo:'',clinical_icons:{},committee:{title:'Scientific Committee',intro:'',published:false,members:[]}};
function fileData(file,max=2200000){return new Promise((resolve,reject)=>{if(!file)return reject(new Error('Seleziona un file.'));if(file.size>max)return reject(new Error('File troppo grande. Usa un file inferiore a 2 MB.'));const r=new FileReader();r.onload=()=>resolve({name:file.name,type:file.type||'application/octet-stream',data:r.result});r.onerror=()=>reject(new Error('Impossibile leggere il file.'));r.readAsDataURL(file)})}
async function uploadFile(file){const payload=await fileData(file);return api('/api/site-admin/media',{method:'POST',body:JSON.stringify(payload)})}
async function loadExtended(){try{const j=await api('/api/site-admin/extended-config');extendedConfig={...extendedConfig,...j.config,clinical_icons:j.config?.clinical_icons||{},committee:{...extendedConfig.committee,...(j.config?.committee||{})}};renderExtended();}catch(e){}try{const m=await api('/api/site-admin/media');renderMedia(m.media||[])}catch(e){}try{const st=await api('/api/site-admin/status');$('buildTime').textContent=st.generated_at?new Date(st.generated_at).toLocaleString('it-IT'):'—';if(Array.isArray(st.clinical_areas)){const sel=$('clinicalAreaSelect');sel.innerHTML=st.clinical_areas.map(a=>`<option value="${esc(a.slug)}" data-icon="${esc(a.icon||'')}">${esc(a.label||a.slug)}</option>`).join('');sel.onchange=renderClinicalPreview;renderClinicalPreview();}}catch(e){}}
function renderExtended(){const photo=extendedConfig.director_photo;$('directorPhotoPreview').src=photo||'https://commons.wikimedia.org/wiki/Special:Redirect/file/Marco_Medeot_portrait.jpg';const c=extendedConfig.committee||{};$('committeeTitle').value=c.title||'Scientific Committee';$('committeeIntro').value=c.intro||'';$('committeePublished').value=String(!!c.published);renderMembers(c.members||[]);renderClinicalPreview();}
function renderClinicalPreview(){const sel=$('clinicalAreaSelect');if(!sel||!sel.value)return;const orig=sel.selectedOptions[0]?.dataset.icon||'';$('clinicalIconPreview').src=extendedConfig.clinical_icons?.[sel.value]||orig||'';}
$('saveDirectorPhoto').onclick=async()=>{try{const m=await uploadFile($('directorPhotoFile').files[0]);extendedConfig.director_photo=m.url;await saveExtended();$('directorPhotoStatus').textContent='Fotografia aggiornata.';}catch(e){$('directorPhotoStatus').textContent=e.message}};
$('resetDirectorPhoto').onclick=async()=>{extendedConfig.director_photo='';await saveExtended();renderExtended();$('directorPhotoStatus').textContent='Fotografia originale ripristinata.'};
$('saveClinicalIcon').onclick=async()=>{try{const slug=$('clinicalAreaSelect').value;if(!slug)throw new Error('Seleziona un’area.');const m=await uploadFile($('clinicalIconFile').files[0]);extendedConfig.clinical_icons[slug]=m.url;await saveExtended();renderClinicalPreview();$('clinicalIconStatus').textContent='Icona aggiornata senza modificare la classificazione.';}catch(e){$('clinicalIconStatus').textContent=e.message}};
$('resetClinicalIcon').onclick=async()=>{const slug=$('clinicalAreaSelect').value;if(slug){delete extendedConfig.clinical_icons[slug];await saveExtended();renderClinicalPreview();$('clinicalIconStatus').textContent='Icona originale ripristinata.'}};
async function saveExtended(){const j=await api('/api/site-admin/extended-config',{method:'PUT',body:JSON.stringify(extendedConfig)});extendedConfig=j.config;return j}
function renderMembers(members){extendedConfig.committee.members=members;$('committeeMembers').innerHTML=members.map((m,i)=>`<div class="member-card" data-mi="${i}"><div class="member-grid"><label>Nome<input data-mk="name" value="${esc(m.name||'')}"></label><label>Ruolo<input data-mk="role" value="${esc(m.role||'')}"></label><label class="wide">Affiliazione<input data-mk="affiliation" value="${esc(m.affiliation||'')}"></label><label>ORCID<input data-mk="orcid" value="${esc(m.orcid||'')}"></label><label>LinkedIn<input data-mk="linkedin" value="${esc(m.linkedin||'')}"></label><label class="wide">Biografia<textarea data-mk="bio" rows="3">${esc(m.bio||'')}</textarea></label><label>Foto URL<input data-mk="photo" value="${esc(m.photo||'')}"></label><label>Curriculum PDF URL<input data-mk="cv" value="${esc(m.cv||'')}"></label></div><div class="toolbar"><label class="btn btn-light">Carica foto<input hidden type="file" accept="image/*" data-member-photo="${i}"></label><label class="btn btn-light">Carica CV<input hidden type="file" accept="application/pdf" data-member-cv="${i}"></label><button class="btn btn-danger" data-member-rm="${i}">Rimuovi membro</button></div></div>`).join('')||'<div class="muted">Nessun membro inserito.</div>';document.querySelectorAll('[data-member-rm]').forEach(b=>b.onclick=()=>{readMembers();const a=extendedConfig.committee.members;a.splice(+b.dataset.memberRm,1);renderMembers(a)});document.querySelectorAll('[data-member-photo]').forEach(inp=>inp.onchange=async()=>{try{readMembers();const m=await uploadFile(inp.files[0]);extendedConfig.committee.members[+inp.dataset.memberPhoto].photo=m.url;renderMembers(extendedConfig.committee.members)}catch(e){$('committeeStatus').textContent=e.message}});document.querySelectorAll('[data-member-cv]').forEach(inp=>inp.onchange=async()=>{try{readMembers();const m=await uploadFile(inp.files[0]);extendedConfig.committee.members[+inp.dataset.memberCv].cv=m.url;renderMembers(extendedConfig.committee.members)}catch(e){$('committeeStatus').textContent=e.message}})}
function readMembers(){document.querySelectorAll('.member-card').forEach(card=>{const m=extendedConfig.committee.members[+card.dataset.mi];card.querySelectorAll('[data-mk]').forEach(x=>m[x.dataset.mk]=x.value.trim())})}
$('addCommitteeMember').onclick=()=>{readMembers();extendedConfig.committee.members.push({name:'',role:'',affiliation:'',bio:'',photo:'',cv:'',orcid:'',linkedin:''});renderMembers(extendedConfig.committee.members)};
$('saveCommittee').onclick=async()=>{try{readMembers();extendedConfig.committee.title=$('committeeTitle').value.trim()||'Scientific Committee';extendedConfig.committee.intro=$('committeeIntro').value.trim();extendedConfig.committee.published=$('committeePublished').value==='true';await saveExtended();$('committeeStatus').textContent='Comitato scientifico salvato.';}catch(e){$('committeeStatus').textContent=e.message}};
function renderMedia(items){$('mediaList').innerHTML=items.map(m=>`<div class="media-card">${m.type?.startsWith('image/')?`<img src="${esc(m.url)}" alt="">`:'<div class="muted">PDF / documento</div>'}<div class="name">${esc(m.name)}</div><a class="btn btn-light" href="${esc(m.url)}" target="_blank">Apri</a> <button class="btn btn-danger" data-media-rm="${esc(m.id)}">Elimina</button></div>`).join('')||'<div class="muted">Nessun media caricato.</div>';document.querySelectorAll('[data-media-rm]').forEach(b=>b.onclick=async()=>{if(!confirm('Eliminare questo file? I contenuti che lo utilizzano potrebbero non visualizzarlo più.'))return;await api('/api/site-admin/media/'+b.dataset.mediaRm,{method:'DELETE'});loadExtended()})}
$('uploadMedia').onclick=async()=>{try{await uploadFile($('mediaFile').files[0]);$('mediaStatus').textContent='File caricato.';loadExtended()}catch(e){$('mediaStatus').textContent=e.message}};
$('downloadBackup').onclick=async()=>{try{const r=await fetch('/api/site-admin/backup',{cache:'no-store'});if(!r.ok)throw new Error('Backup non disponibile.');const blob=await r.blob(),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ketogenicresearch-admin-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e){alert(e.message)}};
loadExtended();
let historyContext={path:'',type:''};
document.querySelectorAll('[data-history]').forEach(b=>b.onclick=async()=>{const type=b.dataset.history,path=$(type==='page'?'pagePath':'articlePath').value;if(!path)return;historyContext={path,type};try{const j=await api('/api/site-admin/history?path='+encodeURIComponent(path));$('historyList').innerHTML=(j.history||[]).map(h=>`<div class="item"><div><b>${new Date(h.saved_at).toLocaleString('it-IT')}</b><div class="muted">${h.state?.deleted?'Contenuto nascosto':h.state?.html?'Versione modificata':'Versione originale'}</div></div><button class="btn btn-light" data-history-id="${esc(h.id)}">Ripristina</button></div>`).join('')||'<div class="muted">Nessuna versione precedente disponibile.</div>';$('historyBox').hidden=false;document.querySelectorAll('[data-history-id]').forEach(x=>x.onclick=async()=>{if(!confirm('Ripristinare questa versione? La versione attuale verrà comunque conservata nella cronologia.'))return;await api('/api/site-admin/history?path='+encodeURIComponent(path),{method:'POST',body:JSON.stringify({id:x.dataset.historyId})});$('historyBox').hidden=true;await loadManifests();await openContent(path,type);});}catch(e){alert(e.message)}});
$('closeHistory').onclick=()=>$('historyBox').hidden=true;
